version: '3.8'

services:
  app:
    image: flowstate-app:latest
    build:
      context: https://github.com/guilhermerodrigues-10/tasks.git#master
      args:
        - VITE_SUPABASE_URL
        - VITE_SUPABASE_ANON_KEY
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - flowstate-network

networks:
  flowstate-network:
    driver: overlay
